# Generated by Django 5.2.7 on 2025-10-31 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('net_income', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('utilities', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('education', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('food', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('transport', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('personal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
