# Generated by Django 5.2.7 on 2025-11-02 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_monthlyfinance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budgetsettings',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='budgetsettings',
            name='start_date',
        ),
        migrations.AddField(
            model_name='budgetsettings',
            name='month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='budgetsettings',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
